[package]
name = "aarch64"
version = "0.1.0"
authors = ["Andrew Walbran <qwandor@google.com>"]
edition = "2021"

[dependencies]
buddy_system_allocator = "0.9.0"
fdt = "0.1.5"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4.17"
smccc = "0.1.1"
spin = "0.9.8"
virtio-drivers = { path = "../.." }

[build-dependencies]
cc = "1.0.73"
